version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-major"]
