title: Site

layout:
    type: sections
    sections:
        info:
            label: '{{admin.options.site.info}}'
            collapsible: true
            fields: [title, author, description]

        advanced:
            label: '{{admin.options.site.advanced}}'
            collapsible: true
            collapsed: true
            fields: [metadata, aliases]

fields:
    title:
        type: text
        label: '{{admin.options.site.info.title}}'
        required: true

    author:
        type: text
        label: '{{admin.options.site.info.author}}'
        default: null


    description:
        type: textarea
        label: '{{admin.options.site.info.description}}'
        default: null

    metadata:
        type: array
        label: '{{admin.options.site.advanced.metadata}}'
        associative: true
        placeholder_key: '{{admin.options.site.advanced.metadata.name}}'
        placeholder_value: '{{admin.options.site.advanced.metadata.content}}'

    aliases:
        type: array
        label: '{{admin.options.site.advanced.aliases}}'
        associative: true
        placeholder_key: '{{admin.options.site.advanced.aliases.alias}}'
        placeholder_value: '{{admin.options.site.advanced.aliases.route}}'
