title: System

layout:
    type: sections
    sections:
        dateTime:
            collapsible: true
            label: '{{panel.options.system.date-and-time}}'
            fields: [date.format, date.time_format, date.timezone, date.week_starts]

        languages:
            collapsible: true
            label: '{{panel.options.system.languages}}'
            fields: [languages.available, languages.http_preferred]

        files:
            collapsible: true
            label: '{{panel.options.system.files}}'
            fields: [files.allowed_extensions]

        cache:
            collapsible: true
            label: '{{panel.options.system.cache}}'
            fields: [cache.enabled, cache.time]

        panel:
            collapsible: true
            label: '{{panel.options.system.admin-panel}}'
            fields: [panel.lang, panel.logout_redirect, panel.session_timeout, panel.color_scheme]

        images:
            collapsible: true
            label: '{{panel.options.system.images}}'
            fields: [images.jpeg_quality, images.png_compression, images.webp_quality, images.jpeg_progressive, images.process_uploads]

        backup:
            collapsible: true
            label: '{{panel.options.system.backup}}'
            fields: [backup.max_files]

fields:
    date.format:
        type: select
        label: '{{panel.options.system.date-and-time.date-format}}'
        import:
            options: 'Formwork\Panel\Utils\DateFormats::date'

    date.time_format:
        type: select
        label: '{{panel.options.system.date-and-time.hour-format}}'
        import:
            options: 'Formwork\Panel\Utils\DateFormats::hour'

    date.timezone:
        type: select
        label: '{{panel.options.system.date-and-time.timezone}}'
        import:
            options: 'Formwork\Panel\Utils\DateFormats::timezones'

    date.week_starts:
        type: select
        label: '{{panel.options.system.date-and-time.first-weekday}}'
        options:
            0: '{{panel.options.system.date-and-time.first-weekday.sunday}}'
            1: '{{panel.options.system.date-and-time.first-weekday.monday}}'

    languages.available:
        type: tags
        label: '{{panel.options.system.languages.available-languages}}'
        placeholder: '{{panel.options.system.languages.available-languages.no-languages}}'
        pattern: '^[a-z]{2,3}$'
        translate: [label, placeholder]
        import:
            options: 'Formwork\Languages\LanguageCodes::names'

    languages.http_preferred:
        type: togglegroup
        label: '{{panel.options.system.languages.preferred-language}}'
        options:
            1: '{{panel.options.system.languages.preferred-language.enabled}}'
            0: '{{panel.options.system.languages.preferred-language.disabled}}'

    files.allowed_extensions:
        type: tags
        label: '{{panel.options.system.files.allowed-extensions}}'
        pattern: '^\.[a-zA-Z0-9]+$'
        required: true

    cache.enabled:
        type: togglegroup
        label: '{{panel.options.system.cache}}'
        options:
            1: '{{panel.options.system.cache.enabled}}'
            0: '{{panel.options.system.cache.disabled}}'

    cache.time:
        type: duration
        label: '{{panel.options.system.cache.time}}'
        min: 900
        step: 900
        intervals: [weeks, days, hours, minutes]
        translate: [label]
        required: true

    panel.lang:
        type: select
        label: '{{panel.options.system.admin-panel.default-language}}'
        translate: [label]
        import:
            options: 'Formwork\Panel\Panel::availableTranslations'

    panel.logout_redirect:
        type: togglegroup
        label: '{{panel.options.system.admin-panel.logout-redirects-to}}'
        options:
            login: '{{panel.options.system.admin-panel.logout-redirects-to.login}}'
            home: '{{panel.options.system.admin-panel.logout-redirects-to.home}}'

    panel.session_timeout:
        type: duration
        label: '{{panel.options.system.admin-panel.session-timeout}}'
        min: 0
        unit: minutes
        intervals: [hours, minutes]
        translate: [label]
        required: true

    panel.color_scheme:
        type: togglegroup
        label: '{{panel.options.system.admin-panel.default-color-scheme}}'
        options:
            light: '{{panel.options.system.admin-panel.default-color-scheme.light}}'
            dark: '{{panel.options.system.admin-panel.default-color-scheme.dark}}'

    images.jpeg_quality:
        type: range
        label: '{{panel.options.system.images.jpeg-quality}}'
        min: 0
        max: 100
        step: 5

    images.png_compression:
        type: range
        label: '{{panel.options.system.images.png-compression-level}}'
        min: 0
        max: 9

    images.webp_quality:
        type: range
        label: '{{panel.options.system.images.webp-quality}}'
        min: 0
        max: 100
        step: 5

    images.jpeg_progressive:
        type: togglegroup
        label: '{{panel.options.system.images.jpeg-save-progressive}}'
        options:
            1: '{{panel.options.system.images.jpeg-save-progressive.enabled}}'
            0: '{{panel.options.system.images.jpeg-save-progressive.disabled}}'

    images.process_uploads:
        type: togglegroup
        label: '{{panel.options.system.images.process-uploads}}'
        options:
            1: '{{panel.options.system.images.process-uploads.enabled}}'
            0: '{{panel.options.system.images.process-uploads.disabled}}'

    backup.max_files:
        type: select
        label: '{{panel.options.system.backup.backup-files-to-keep}}'
        options:
            5: 5
            10: 10
            15: 15
            20: 20
